// dummyData.ts
// Ei file ta temporary. Real API ashle, ei imports gula
// RTK Query endpoint hook diye replace hobe:
//   const { data } = useGetAvailabilityQuery();
// Response shape same rakha hoyeche (types.ts dekho) jate
// component-level kono change lagbe na.

import {
  AvailabilityApiResponse,
  BookingInboxApiResponse,
  MessagesApiResponse,
  ProfileApiResponse,
} from "./types";

export const availabilityDummyResponse: AvailabilityApiResponse = {
  success: true,
  data: {
    todayStatus: {
      date: "Thursday, July 2",
      isAvailableToday: true,
      workingHours: "9:00 AM – 6:00 PM",
      nextBooking: "2:00 PM",
    },
    bookingSummary: {
      todaysBookings: 3,
      availableHours: 9,
      blockedDates: 2,
      vacationDays: 0,
    },
    weeklySchedule: [
      {
        day: "Monday",
        isActive: true,
        startTime: "09:00 AM",
        endTime: "06:00 PM",
        hasBreak: true,
        breakFrom: "01:00 PM",
        breakTo: "02:00 PM",
        hasEveningSession: false,
      },
      {
        day: "Tuesday",
        isActive: true,
        startTime: "09:00 AM",
        endTime: "06:00 PM",
        hasBreak: false,
        hasEveningSession: false,
      },
      {
        day: "Wednesday",
        isActive: true,
        startTime: "10:00 AM",
        endTime: "05:00 PM",
        hasBreak: false,
        hasEveningSession: false,
      },
      {
        day: "Thursday",
        isActive: true,
        startTime: "09:00 AM",
        endTime: "06:00 PM",
        hasBreak: false,
        hasEveningSession: false,
      },
      {
        day: "Friday",
        isActive: true,
        startTime: "09:00 AM",
        endTime: "04:00 PM",
        hasBreak: false,
        hasEveningSession: false,
      },
      {
        day: "Saturday",
        isActive: true,
        startTime: "10:00 AM",
        endTime: "03:00 PM",
        hasBreak: false,
        hasEveningSession: false,
      },
      {
        day: "Sunday",
        isActive: false,
        startTime: null,
        endTime: null,
        hasBreak: false,
        hasEveningSession: false,
      },
    ],
    calendar: {
      month: "July 2026",
      days: [
        { date: "2026-07-01", day: 1, status: "none" },
        { date: "2026-07-02", day: 2, status: "today" },
        { date: "2026-07-03", day: 3, status: "booked" },
        { date: "2026-07-04", day: 4, status: "booked" },
        { date: "2026-07-05", day: 5, status: "none" },
        { date: "2026-07-06", day: 6, status: "available" },
        { date: "2026-07-07", day: 7, status: "available" },
        { date: "2026-07-08", day: 8, status: "available" },
        { date: "2026-07-09", day: 9, status: "booked" },
        { date: "2026-07-10", day: 10, status: "blocked" },
        { date: "2026-07-11", day: 11, status: "blocked" },
        { date: "2026-07-12", day: 12, status: "available" },
        { date: "2026-07-13", day: 13, status: "available" },
        { date: "2026-07-14", day: 14, status: "available" },
        { date: "2026-07-15", day: 15, status: "booked" },
        { date: "2026-07-16", day: 16, status: "available" },
        { date: "2026-07-17", day: 17, status: "booked" },
        { date: "2026-07-18", day: 18, status: "available" },
        { date: "2026-07-19", day: 19, status: "available" },
        { date: "2026-07-20", day: 20, status: "available" },
        { date: "2026-07-21", day: 21, status: "available" },
        { date: "2026-07-22", day: 22, status: "booked" },
        { date: "2026-07-23", day: 23, status: "available" },
        { date: "2026-07-24", day: 24, status: "available" },
        { date: "2026-07-25", day: 25, status: "booked" },
        { date: "2026-07-26", day: 26, status: "available" },
        { date: "2026-07-27", day: 27, status: "available" },
        { date: "2026-07-28", day: 28, status: "available" },
        { date: "2026-07-29", day: 29, status: "available" },
        { date: "2026-07-30", day: 30, status: "available" },
        { date: "2026-07-31", day: 31, status: "available" },
      ],
    },
    blockedDates: [
      {
        id: "bd_1",
        date: "2026-07-10",
        label: "Fri, Jul 10",
        reason: "Personal Work · Client sch",
      },
      {
        id: "bd_2",
        date: "2026-07-11",
        label: "Sat, Jul 11",
        reason: "Holiday",
      },
    ],
    vacationMode: { enabled: false },
    recurringSchedule: {
      weeklyRepeat: true,
      monthlyRepeat: false,
      weekdaysOnly: true,
      customDays: false,
    },
    instantBooking: {
      enabled: true,
      minimumNoticeHours: 2,
      bookingBufferMinutes: 30,
      maxPerDay: 8,
    },
  },
};

export const bookingInboxDummyResponse: BookingInboxApiResponse = {
  success: true,
  data: {
    summary: { requests: 3, pending: 1, accepted: 2, earnings: 280 },
    bookings: [
      {
        id: "bk_1",
        bookingRefId: "BK-20260702-001",
        client: {
          name: "Sophia Williams",
          avatarUrl: "https://i.pravatar.cc/150?img=47",
          isVerified: true,
        },
        service: "Full Glam Makeup",
        status: "new",
        requestedAt: "10 min ago",
        date: "Today, Jul 2",
        time: "2:00 PM",
        durationMinutes: 90,
        visitType: "Home Visit",
        location: "123 Maple Street, Beverly Hil",
        amount: 280,
      },
      {
        id: "bk_2",
        bookingRefId: "BK-20260702-002",
        client: {
          name: "Priya Sharma",
          avatarUrl: "https://i.pravatar.cc/150?img=32",
          isVerified: true,
        },
        service: "Bridal Makeup Package",
        status: "accepted",
        requestedAt: "1 hr ago",
        date: "Today, Jul 2",
        time: "4:00 PM",
        durationMinutes: 120,
        visitType: "Home Visit",
        location: "45 Rose Avenue, Malib",
        amount: 420,
      },
      {
        id: "bk_3",
        bookingRefId: "BK-20260703-005",
        client: {
          name: "Amara Johnson",
          avatarUrl: "https://i.pravatar.cc/150?img=25",
          isVerified: false,
        },
        service: "Evening Glam Look",
        status: "pending",
        requestedAt: "2 hrs ago",
        date: "Tomorrow, Jul 3",
        time: "11:00 AM",
        durationMinutes: 60,
        visitType: "Home Visit",
        location: "88 Sunset Blvd, Los Angel",
        amount: 180,
      },
      {
        id: "bk_4",
        bookingRefId: "BK-20260628-001",
        client: {
          name: "Camille Laurent",
          avatarUrl: "https://i.pravatar.cc/150?img=45",
          isVerified: true,
        },
        service: "Bridal Hair + Full Makeup",
        status: "completed",
        requestedAt: "Jun 28, 2026",
        date: "Jun 28, 2026",
        time: "180 min",
        durationMinutes: 180,
        visitType: "Home Visit",
        location: "Los Angeles",
        amount: 680,
        review: {
          rating: 5.0,
          comment:
            "Made my wedding day absolutely perfect. So professional, so talented.",
        },
      },
    ],
  },
};

export const messagesDummyResponse: MessagesApiResponse = {
  success: true,
  data: {
    chats: [
      {
        id: "chat_1",
        clientName: "Sophia Williams",
        clientInitials: "SW",
        bookingRefId: "BK-20250628-001",
        lastMessage: "Thank you so much! See you tomor...",
        timestamp: "2m ago",
        unreadCount: 0,
        status: "Booking Active",
        isOnline: true,
        avatarColor: "#FBD3D3",
      },
      {
        id: "chat_2",
        clientName: "Emma Johnson",
        clientInitials: "EJ",
        bookingRefId: "BK-20250625-003",
        lastMessage: "Can we reschedule to 3pm?",
        timestamp: "1h ago",
        unreadCount: 2,
        status: "Booking Active",
        isOnline: false,
        avatarColor: "#D6F0DC",
      },
      {
        id: "chat_3",
        clientName: "Ava Martinez",
        clientInitials: "AM",
        bookingRefId: "BK-20250618-007",
        lastMessage: "Perfect! I'll be there on time.",
        timestamp: "3h ago",
        unreadCount: 0,
        status: "Completed",
        isOnline: true,
        avatarColor: "#FCE7C6",
      },
      {
        id: "chat_4",
        clientName: "Isabella Kim",
        clientInitials: "IK",
        bookingRefId: "BK-20250610-012",
        lastMessage: "Looking forward to it!",
        timestamp: "Yesterday",
        unreadCount: 1,
        status: "Completed",
        isOnline: false,
        avatarColor: "#E7DCF5",
      },
      {
        id: "chat_5",
        clientName: "Olivia Brown",
        clientInitials: "OB",
        bookingRefId: "BK-20250702-015",
        lastMessage: "Hi, can you confirm my appointment time?",
        timestamp: "5m ago",
        unreadCount: 1,
        status: "Booking Active",
        isOnline: true,
        avatarColor: "#FDE2E4",
      },
      {
        id: "chat_6",
        clientName: "Mia Anderson",
        clientInitials: "MA",
        bookingRefId: "BK-20250701-009",
        lastMessage: "Thank you! The service was amazing.",
        timestamp: "25m ago",
        unreadCount: 0,
        status: "Completed",
        isOnline: false,
        avatarColor: "#D9F7E8",
      },
      {
        id: "chat_7",
        clientName: "Charlotte Davis",
        clientInitials: "CD",
        bookingRefId: "BK-20250630-021",
        lastMessage: "Is it possible to change the location?",
        timestamp: "1h ago",
        unreadCount: 2,
        status: "Booking Active",
        isOnline: true,
        avatarColor: "#FFF1CC",
      },
      {
        id: "chat_8",
        clientName: "Amelia Wilson",
        clientInitials: "AW",
        bookingRefId: "BK-20250627-018",
        lastMessage: "I have uploaded the reference photos.",
        timestamp: "2h ago",
        unreadCount: 0,
        status: "Booking Active",
        isOnline: false,
        avatarColor: "#E8DEF8",
      },
      {
        id: "chat_9",
        clientName: "Harper Taylor",
        clientInitials: "HT",
        bookingRefId: "BK-20250622-005",
        lastMessage: "Can we move my appointment to Friday?",
        timestamp: "Yesterday",
        unreadCount: 3,
        status: "Booking Active",
        isOnline: false,
        avatarColor: "#DDEBF7",
      },
      {
        id: "chat_10",
        clientName: "Evelyn Martinez",
        clientInitials: "EM",
        bookingRefId: "BK-20250620-014",
        lastMessage: "Everything was perfect. Thank you!",
        timestamp: "Yesterday",
        unreadCount: 0,
        status: "Completed",
        isOnline: true,
        avatarColor: "#FFE4E6",
      },
      {
        id: "chat_11",
        clientName: "Sophia Miller",
        clientInitials: "SM",
        bookingRefId: "BK-20250615-011",
        lastMessage: "Could you please share the pricing details?",
        timestamp: "2 days ago",
        unreadCount: 1,
        status: "Booking Active",
        isOnline: false,
        avatarColor: "#DCFCE7",
      },
      {
        id: "chat_12",
        clientName: "Grace Thompson",
        clientInitials: "GT",
        bookingRefId: "BK-20250612-019",
        lastMessage: "Thanks for your quick response!",
        timestamp: "3 days ago",
        unreadCount: 0,
        status: "Completed",
        isOnline: false,
        avatarColor: "#FCE7F3",
      },
      {
        id: "chat_13",
        clientName: "Ella Robinson",
        clientInitials: "ER",
        bookingRefId: "BK-20250608-022",
        lastMessage: "I would like to book another session.",
        timestamp: "4 days ago",
        unreadCount: 1,
        status: "Completed",
        isOnline: true,
        avatarColor: "#E0F2FE",
      },
      {
        id: "chat_14",
        clientName: "Isla Thompson",
        clientInitials: "IT",
        bookingRefId: "BK-20250605-013",
        lastMessage: "Please let me know your availability.",
        timestamp: "5 days ago",
        unreadCount: 0,
        status: "Booking Active",
        isOnline: false,
        avatarColor: "#F5E6CC",
      },
    ],
  },
};

export const profileDummyResponse: ProfileApiResponse = {
  success: true,
  data: {
    name: "Sophie Laurent",
    role: "Hair & Makeup Artist",
    isVerified: true,
    avatarUrl: "https://i.pravatar.cc/300?img=44",
    coverAvatarUrl: "https://i.pravatar.cc/100?img=44",
    experienceYears: 8,
    rating: 4.9,
    reviewsCount: 271,
    profileCompletionPercent: 95,
    portfolio: [
      { id: "p1", imageUrl: "https://picsum.photos/seed/port1/300/300" },
      { id: "p2", imageUrl: "https://picsum.photos/seed/port2/300/300" },
      { id: "p3", imageUrl: "https://picsum.photos/seed/port3/300/300" },
    ],
    services: [
      { id: "s1", name: "Hair Styling", durationMinutes: 60, price: 85 },
      { id: "s2", name: "Hair Color", durationMinutes: 120, price: 160 },
      { id: "s3", name: "Bridal Makeup", durationMinutes: 90, price: 220 },
      { id: "s4", name: "Facial", durationMinutes: 45, price: 95 },
      { id: "s5", name: "Nail Services", durationMinutes: 60, price: 70 },
      { id: "s6", name: "Massage", durationMinutes: 60, price: 110 },
    ],
    businessInfo: {
      businessName: "Lumière Beauty Studio",
      abnNumber: "12 345 678 901",
      abnVerified: true,
      address: "42 Crown St, Surry Hills NSW 2010",
      workingHours: "Mon–Sat · 9:00 AM – 7:00 PM",
      travelRadiusKm: 25,
      languages: ["English", "French"],
      memberSince: "March 2018",
    },
  },
};
